version: '3.8'
services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3008:80"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
